name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: logz
            asset_name: logz-linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_name: logz.exe
            asset_name: logz-windows-x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: logz
            asset_name: logz-macos-x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare release archive (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/${{ matrix.binary_name }} release/
          strip release/${{ matrix.binary_name }}
          tar -czf ${{ matrix.asset_name }}.tar.gz -C release .

      - name: Prepare release archive (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir release
          cp target/${{ matrix.target }}/release/${{ matrix.binary_name }} release/
          Compress-Archive -Path release/* -DestinationPath ${{ matrix.asset_name }}.zip

      - name: Upload release asset
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: |
            ${{ matrix.asset_name }}.tar.gz
            ${{ matrix.asset_name }}.zip

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            logz-linux-x86_64/logz-linux-x86_64.tar.gz
            logz-windows-x86_64/logz-windows-x86_64.zip
            logz-macos-x86_64/logz-macos-x86_64.tar.gz